# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 03:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import threedbang.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('detail_address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('name_user', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='프리 프린팅 신청 여부(O,X)', max_length=255)),
                ('file', models.FileField(upload_to=threedbang.models.user_path)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('volume', models.IntegerField(default=0)),
                ('price', models.CharField(default='검토중', max_length=255)),
                ('time', models.CharField(default='검토중', max_length=255)),
                ('thumnail_image', models.ImageField(blank=True, upload_to='')),
                ('filenamemake', models.CharField(max_length=255)),
                ('fdm_material_price', models.IntegerField(blank=True, default=0)),
                ('fdm_time', models.IntegerField(blank=True, default=0)),
                ('fdm_machine_price', models.IntegerField(blank=True, default=0)),
                ('fdm_sum_price', models.IntegerField(blank=True, default=0)),
                ('sla_material_price', models.IntegerField(blank=True, default=0)),
                ('sla_time', models.IntegerField(blank=True, default=0)),
                ('sla_machine_price', models.IntegerField(blank=True, default=0)),
                ('sla_sum_price', models.IntegerField(blank=True, default=0)),
                ('sla_sum_time', models.IntegerField(blank=True, default=0)),
                ('fdm_sum_time', models.IntegerField(blank=True, default=0)),
                ('test_a', models.CharField(blank=True, max_length=255)),
                ('test_b', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customaddress',
            name='stlfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threedbang.StlFile'),
        ),
    ]
